# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySS
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'MySSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MySSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
